CREATE TABLE instituicao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    id UUID PRIMARY KEY,
    login VARCHAR(80) NOT NULL UNIQUE,
    senha_hash VARCHAR(100) NOT NULL,
    perfil VARCHAR(20) NOT NULL CHECK (perfil IN ('ALUNO', 'EMPRESA', 'PROFESSOR')),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE aluno (
    id UUID PRIMARY KEY REFERENCES usuario(id),
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE CHECK (cpf ~ '^[0-9]{11}$'),
    rg VARCHAR(30) NOT NULL,
    endereco VARCHAR(300) NOT NULL,
    curso VARCHAR(150) NOT NULL,
    instituicao_id BIGINT NOT NULL REFERENCES instituicao(id)
);
CREATE INDEX idx_aluno_instituicao ON aluno(instituicao_id);

CREATE TABLE empresa_parceira (
    id UUID PRIMARY KEY REFERENCES usuario(id),
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL
);

CREATE TABLE conta (
    id UUID PRIMARY KEY,
    titular_id UUID NOT NULL UNIQUE REFERENCES usuario(id),
    saldo BIGINT NOT NULL DEFAULT 0 CHECK (saldo >= 0),
    versao BIGINT NOT NULL DEFAULT 0
);
